/**
 * Stripe Price IDs
 * Generated by scripts/setup-stripe-products.mjs
 *
 * These are LIVE price IDs - do not commit test IDs to production
 */

export const STRIPE_PRICE_IDS = {
  // Service Packages
  MATCH_READY_SERVICE: 'price_1SiiF1Hs3wHBptAbmwhkWDXN',
  PRO_PERFORMANCE_SERVICE: 'price_1SiiF2Hs3wHBptAbdPvEzVg0',

  // Strings
  STRING_WILSON_VELOCITY_MLT: 'price_1SiiF2Hs3wHBptAbGTSv6hOp',
  STRING_BABOLAT_RPM_BLAST: 'price_1SiiF3Hs3wHBptAbNjnBQ42o',
  STRING_LUXILON_ALU_POWER: 'price_1SiiF4Hs3wHBptAbUx69hsDW',
  STRING_WILSON_NXT: 'price_1SiiF5Hs3wHBptAbknqL1TPK',
  STRING_SOLINCO_CONFIDENTIAL: 'price_1SiiF6Hs3wHBptAbE7Apl1St',
  STRING_TECNIFIBRE_XONE: 'price_1SiiF6Hs3wHBptAbfxDelDux',
  STRING_PRINCE_SYNTHETIC_GUT: 'price_1SiiF7Hs3wHBptAb6N1y0YrO',
  STRING_VOLKL_CYCLONE: 'price_1SiiF8Hs3wHBptAbzhmGu2HI',

  // Add-ons
  ADDON_EXPRESS: 'price_1SiiF9Hs3wHBptAb3240LRzU',
  ADDON_REGRIP: 'price_1SiiFAHs3wHBptAb2ixYyy28',
  ADDON_OVERGRIP: 'price_1SiiFBHs3wHBptAbFIgY2FOO',
  ADDON_DAMPENER: 'price_1SiiFBHs3wHBptAbm0dFUnQT',
  ADDON_DAMPENER_BUNDLE: 'price_1SiiFCHs3wHBptAb1S653gkT',
  PICKUP_DELIVERY_FEE: 'price_1SiiFDHs3wHBptAbzHeiMxpf',

  // Memberships (Recurring)
  MEMBERSHIP_STANDARD: 'price_1SiiFEHs3wHBptAbHtvnC17A',
  MEMBERSHIP_ELITE: 'price_1SiiFFHs3wHBptAbTP5pu18A',
  MEMBERSHIP_FAMILY: 'price_1SiiFFHs3wHBptAbkUdk1Ekg',

  // Bundle Packages
  PACKAGE_STARTER: 'price_1SiiFGHs3wHBptAbCiXMN9BG',
  PACKAGE_PRO: 'price_1SiiFHHs3wHBptAb6STVawLo',
} as const

// Helper type for type-safe price ID access
export type StripePriceId = typeof STRIPE_PRICE_IDS[keyof typeof STRIPE_PRICE_IDS]

// String name to price ID mapping
export const STRING_PRICE_MAP: Record<string, string> = {
  'wilson-velocity-mlt': STRIPE_PRICE_IDS.STRING_WILSON_VELOCITY_MLT,
  'babolat-rpm-blast': STRIPE_PRICE_IDS.STRING_BABOLAT_RPM_BLAST,
  'luxilon-alu-power': STRIPE_PRICE_IDS.STRING_LUXILON_ALU_POWER,
  'wilson-nxt': STRIPE_PRICE_IDS.STRING_WILSON_NXT,
  'solinco-confidential': STRIPE_PRICE_IDS.STRING_SOLINCO_CONFIDENTIAL,
  'tecnifibre-xone': STRIPE_PRICE_IDS.STRING_TECNIFIBRE_XONE,
  'prince-synthetic-gut': STRIPE_PRICE_IDS.STRING_PRINCE_SYNTHETIC_GUT,
  'volkl-cyclone': STRIPE_PRICE_IDS.STRING_VOLKL_CYCLONE,
}
